### ISSUE TITLE
FFI::NullPointerError: invalid memory read at address=0x0000000000000000

### ISSUE THREAD

**Issue by kochd** [Nakilon/dhash-vips#1]
<pre>
[40] pry(main)> DHashVips::DHash.calculate("00001.jpg")
vips warning: tilecache: error in tile 0 x 0
FFI::NullPointerError: invalid memory read at address=0x0000000000000000
from /var/lib/gems/2.5.0/gems/ruby-vips-2.0.12/lib/vips/image.rb:478:in `get_bytes'
[41] pry(main)> DHashVips::IDHash.fingerprint("00001.jpg")
vips warning: tilecache: error in tile 0 x 0
FFI::NullPointerError: invalid memory read at address=0x0000000000000000
from /var/lib/gems/2.5.0/gems/ruby-vips-2.0.12/lib/vips/image.rb:478:in `get_bytes'
</pre>
<pre>
dpkg -l | grep libvips-dev
ii  libvips-dev                                     8.4.5-2+b1                              amd64        image processing system good for very large ones (dev)
</pre>
<pre>
cat /etc/issue.net 
Debian GNU/Linux buster/sid
</pre>

**Comment by Nakilon** [comment]
Existing similar issues are all about some memory leaks: https://github.com/jcupitt/ruby-vips/search?q=0x0000000000000000&type=Issues

Here is my environment:
```
$ bundle exec gem list
...
ffi (1.9.23)
...
ruby-vips (2.0.12)
```
```
$ vips -v
vips-8.6.3-Thu Mar  8 15:18:35 UTC 2018
```
and I never had this error.

Maybe @jcupitt can tell how to debug it.

**Comment by kochd** [comment]
ffi (1.9.23)
ruby-vips (2.0.12)
ruby 2.5.1p57 (2018-03-29 revision 63029) [x86_64-linux-gnu]

Memoryleak is not an option. I get this error instantly,

<pre>

$ ruby -r 'dhash-vips' -e 'DHashVips::DHash.calculate("00001.jpg")'
vips warning: tilecache: error in tile 0 x 0
Traceback (most recent call last):
	4: from -e:1:in `<main>'
	3: from /var/lib/gems/2.5.0/gems/dhash-vips-0.0.6.0/lib/dhash-vips.rb:24:in `calculate'
	2: from /var/lib/gems/2.5.0/gems/ruby-vips-2.0.12/lib/vips/image.rb:951:in `to_a'
	1: from /var/lib/gems/2.5.0/gems/ruby-vips-2.0.12/lib/vips/image.rb:478:in `write_to_memory'
/var/lib/gems/2.5.0/gems/ruby-vips-2.0.12/lib/vips/image.rb:478:in `get_bytes': invalid memory read at address=0x0000000000000000 (FFI::NullPointerError)
</pre>

**Comment by jcupitt** [comment]
Huh how weird!

ruby-vips has some logging stuff, could you try enabling that and post the output? I see:

```
john@kiwi:~/pics$ irb
irb(main):001:0> require 'logger'
=> true
irb(main):002:0> require 'vips'
=> true
irb(main):003:0> GLib::logger.level = Logger::DEBUG
=> 0
irb(main):004:0> require 'dhash-vips'
=> true
irb(main):005:0> DHashVips::DHash.calculate "k2.jpg"
D, [2018-05-12T12:09:45.626653 #18885] DEBUG -- Vips::VipsOperation.call: name = VipsForeignLoadJpegFile, supplied = ["k2.jpg"], optional = {}, option_string = 
D, [2018-05-12T12:09:45.630126 #18885] DEBUG -- Vips::Object.set: filename = k2.jpg
D, [2018-05-12T12:09:45.630687 #18885] DEBUG -- Vips::Object.get: out == #<Vips::Image:0x0000563baaf485f8>
D, [2018-05-12T12:09:45.630737 #18885] DEBUG -- Vips::Operation.call: result = #<Vips::Image:0x0000563baaf485f8>
D, [2018-05-12T12:09:45.631261 #18885] DEBUG -- Vips::VipsOperation.call: name = resize, supplied = [#<Image 1450x2048 uchar, 3 bands, srgb>, 0.006206896551724138], optional = {:vscale=>0.00390625}, option_string = 
D, [2018-05-12T12:09:45.631449 #18885] DEBUG -- Vips::Object.set: in = #<Vips::Image:0x0000563baaf485f8>
D, [2018-05-12T12:09:45.631581 #18885] DEBUG -- Vips::Object.set: scale = 0.006206896551724138
D, [2018-05-12T12:09:45.631656 #18885] DEBUG -- Vips::Object.set: vscale = 0.00390625
D, [2018-05-12T12:09:45.634616 #18885] DEBUG -- Vips::Object.get: out == #<Vips::Image:0x0000563baaf42040>
D, [2018-05-12T12:09:45.634716 #18885] DEBUG -- Vips::Operation.call: result = #<Vips::Image:0x0000563baaf42040>
D, [2018-05-12T12:09:45.635359 #18885] DEBUG -- Vips::VipsOperation.call: name = colourspace, supplied = [#<Image 9x8 uchar, 3 bands, srgb>, "b-w"], optional = {}, option_string = 
D, [2018-05-12T12:09:45.635619 #18885] DEBUG -- Vips::Object.set: in = #<Vips::Image:0x0000563baaf42040>
D, [2018-05-12T12:09:45.635825 #18885] DEBUG -- Vips::Object.set: space = b-w
D, [2018-05-12T12:09:45.636312 #18885] DEBUG -- Vips::Object.get: out == #<Vips::Image:0x0000563bab1de6a0>
D, [2018-05-12T12:09:45.636374 #18885] DEBUG -- Vips::Operation.call: result = #<Vips::Image:0x0000563bab1de6a0>
D, [2018-05-12T12:09:45.637087 #18885] DEBUG -- Vips::VipsOperation.call: name = cast, supplied = [#<Image 9x8 uchar, 1 bands, b-w>, "int"], optional = {}, option_string = 
D, [2018-05-12T12:09:45.637282 #18885] DEBUG -- Vips::Object.set: in = #<Vips::Image:0x0000563bab1de6a0>
D, [2018-05-12T12:09:45.637508 #18885] DEBUG -- Vips::Object.set: format = int
D, [2018-05-12T12:09:45.637874 #18885] DEBUG -- Vips::Object.get: out == #<Vips::Image:0x0000563bab116970>
D, [2018-05-12T12:09:45.637934 #18885] DEBUG -- Vips::Operation.call: result = #<Vips::Image:0x0000563bab116970>
D, [2018-05-12T12:09:45.638592 #18885] DEBUG -- Vips::VipsOperation.call: name = conv, supplied = [#<Image 9x8 int, 1 bands, b-w>, [1, -1]], optional = {}, option_string = 
D, [2018-05-12T12:09:45.638783 #18885] DEBUG -- Vips::Object.set: in = #<Vips::Image:0x0000563bab116970>
D, [2018-05-12T12:09:45.639309 #18885] DEBUG -- Vips::Object.set: mask = #<Vips::Image:0x0000563bab1537d0>
D, [2018-05-12T12:09:45.643642 #18885] DEBUG -- Vips::Object.get: out == #<Vips::Image:0x0000563bab137e68>
D, [2018-05-12T12:09:45.643740 #18885] DEBUG -- Vips::Operation.call: result = #<Vips::Image:0x0000563bab137e68>
D, [2018-05-12T12:09:45.644673 #18885] DEBUG -- Vips::VipsOperation.call: name = crop, supplied = [#<Image 9x8 float, 1 bands, b-w>, 1, 0, 8, 8], optional = {}, option_string = 
D, [2018-05-12T12:09:45.644901 #18885] DEBUG -- Vips::Object.set: input = #<Vips::Image:0x0000563bab137e68>
D, [2018-05-12T12:09:45.645102 #18885] DEBUG -- Vips::Object.set: left = 1
D, [2018-05-12T12:09:45.645225 #18885] DEBUG -- Vips::Object.set: top = 0
D, [2018-05-12T12:09:45.645344 #18885] DEBUG -- Vips::Object.set: width = 8
D, [2018-05-12T12:09:45.645512 #18885] DEBUG -- Vips::Object.set: height = 8
D, [2018-05-12T12:09:45.645757 #18885] DEBUG -- Vips::Object.get: out == #<Vips::Image:0x0000563bab1053c8>
D, [2018-05-12T12:09:45.645817 #18885] DEBUG -- Vips::Operation.call: result = #<Vips::Image:0x0000563bab1053c8>
D, [2018-05-12T12:09:45.646772 #18885] DEBUG -- Vips::VipsOperation.call: name = relational_const, supplied = [#<Image 8x8 float, 1 bands, b-w>, :more, 0], optional = {}, option_string = 
D, [2018-05-12T12:09:45.647008 #18885] DEBUG -- Vips::Object.set: in = #<Vips::Image:0x0000563bab1053c8>
D, [2018-05-12T12:09:45.647220 #18885] DEBUG -- Vips::Object.set: relational = more
D, [2018-05-12T12:09:45.647296 #18885] DEBUG -- Vips::Object.set: c = 0
D, [2018-05-12T12:09:45.647604 #18885] DEBUG -- Vips::Object.get: out == #<Vips::Image:0x0000563bab0d65c8>
D, [2018-05-12T12:09:45.647640 #18885] DEBUG -- Vips::Operation.call: result = #<Vips::Image:0x0000563bab0d65c8>
D, [2018-05-12T12:09:45.648115 #18885] DEBUG -- Vips::VipsOperation.call: name = linear, supplied = [#<Image 8x8 uchar, 1 bands, b-w>, 0.00392156862745098, 0], optional = {}, option_string = 
D, [2018-05-12T12:09:45.648254 #18885] DEBUG -- Vips::Object.set: in = #<Vips::Image:0x0000563bab0d65c8>
D, [2018-05-12T12:09:45.648394 #18885] DEBUG -- Vips::Object.set: a = 0.00392156862745098
D, [2018-05-12T12:09:45.648465 #18885] DEBUG -- Vips::Object.set: b = 0
D, [2018-05-12T12:09:45.648690 #18885] DEBUG -- Vips::Object.get: out == #<Vips::Image:0x0000563bab0ac138>
D, [2018-05-12T12:09:45.648722 #18885] DEBUG -- Vips::Operation.call: result = #<Vips::Image:0x0000563bab0ac138>
D, [2018-05-12T12:09:45.649211 #18885] DEBUG -- Vips::VipsOperation.call: name = cast, supplied = [#<Image 8x8 float, 1 bands, b-w>, "uchar"], optional = {}, option_string = 
D, [2018-05-12T12:09:45.649372 #18885] DEBUG -- Vips::Object.set: in = #<Vips::Image:0x0000563bab0ac138>
D, [2018-05-12T12:09:45.649537 #18885] DEBUG -- Vips::Object.set: format = uchar
D, [2018-05-12T12:09:45.649788 #18885] DEBUG -- Vips::Object.get: out == #<Vips::Image:0x0000563bab07f3e0>
D, [2018-05-12T12:09:45.649825 #18885] DEBUG -- Vips::Operation.call: result = #<Vips::Image:0x0000563bab07f3e0>
=> 7911847136533597595
```

**Comment by Nakilon** [comment]
@kochd do you still experience the issue? Or did you upgrade the libvips and it's gone? Or is the issue not important anymore?
